locationName = "new york City"
print(locationName.capitalize())
print(locationName.casefold())
print(locationName.center(30, '*'))
print(locationName.count('o'))
print(locationName.encode())

print(locationName.title())

print(locationName.endswith('city'))
print(locationName.expandtabs())
print(locationName.find('w'))
print(locationName.format())

print(locationName.index('n'))
print(locationName.isalnum())
print(locationName.isalpha())
print(locationName.isdecimal())
print(locationName.isdigit())
print(locationName.islower())
print(locationName.isnumeric())
print(locationName.isprintable())
print(locationName.isspace())
print(locationName.istitle())
print(locationName.isupper())
print(locationName.join(['Welcome to ', '!']))
print(locationName.ljust(30, '-'))
print(locationName.lower())
print(locationName.lstrip())
print(locationName.partition('y'))
print(locationName.replace('y', 'Y'))
print(locationName.rfind('o'))
print(locationName.rindex('c'))
print(locationName.rjust(30, '+'))
print(locationName.rstrip())
print(locationName.split(' '))
print(locationName.splitlines())
print(locationName.startswith('new'))
print(locationName.strip())
print(locationName.swapcase())

print(locationName.upper())
print(locationName.zfill(50))
